routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PaidController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ChequeController;
use App\Http\Controllers\PendingController;
use App\Http\Controllers\PeminjamController;
use App\Http\Controllers\PinjamanController;
use App\Http\Controllers\VerificationController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('user.content');
// });


Auth::routes();

Route::get('/', function () {
    return redirect(route('login'));
});

Route::group(['middleware' => 'auth'], function() {

Route::get('/dashboard', [HomeController::class, 'index'])->name('home');
Route::get('/profil', [UserController::class, 'profil'])->name('profil');


// DATA JSON
Route::get('/user/datajson', [UserController::class, 'dataJson'])->name('user.json');
Route::get('/peminjam/datajson', [PeminjamController::class, 'dataJson'])->name('peminjam.json');
Route::get('/peminjam/pinjaman/datajson', [PeminjamController::class, 'dataJson_pinjaman'])->name('peminjam.pinjam.json');
Route::get('/pinjaman/datajson/{id}', [PinjamanController::class, 'dataJson'])->name('pinjaman.json');
Route::get('/verification/datajson/{id}', [VerificationController::class, 'dataJson_pinjaman'])->name('verif.json');
Route::get('/verification/peminjam/datajson', [VerificationController::class, 'dataJson_peminjam'])->name('peminjam.verif.json');
Route::get('/pending/datajson/{id}', [PendingController::class, 'dataJson_pinjaman'])->name('pending.json');
Route::get('/pending/peminjam/datajson', [PendingController::class, 'dataJson_peminjam'])->name('peminjam.pending.json');
Route::get('/paid/datajson/{id}', [PaidController::class, 'dataJson_pinjaman'])->name('paid.json');
Route::get('/paid/peminjam/datajson', [PaidController::class, 'dataJson_peminjam'])->name('peminjam.paid.json');
Route::get('/cheque/datajson', [ChequeController::class, 'dataJson'])->name('cheque.json');

Route::patch('/ubah_pass', [UserController::class, 'ubah_pass'])->name('ubah_pass');
Route::get('/peminjam/pinjaman/{id}', [PinjamanController::class, 'index_pinjaman'])->name('peminjam.pinjaman');


Route::get('verification', [VerificationController::class, 'index'])->name('index.verification');
Route::post('verification/update', [VerificationController::class, 'verif'])->name('update.verif');
Route::get('/peminjam/verification/{id}', [VerificationController::class, 'index_pinjaman'])->name('peminjam.verif');

Route::get('pending', [PendingController::class, 'index'])->name('index.pending');
Route::post('pending/update', [PendingController::class, 'pending'])->name('update.pending');
Route::get('/peminjam/pending/{id}', [PendingController::class, 'index_pinjaman'])->name('peminjam.pending');

Route::get('pending', [PendingController::class, 'index'])->name('index.pending');
Route::post('pending/update', [PendingController::class, 'pending'])->name('update.pending');
Route::get('/peminjam/pending/{id}', [PendingController::class, 'index_pinjaman'])->name('peminjam.pending');

Route::get('paid', [PaidController::class, 'index'])->name('index.paid');
Route::get('/peminjam/paid/{id}', [PaidController::class, 'index_pinjaman'])->name('peminjam.paid');

Route::get('riwayat/{id}', [PaidController::class, 'riwayat'])->name('riwayat');
Route::get('invoice/{id}', [PendingController::class, 'invoice'])->name('invoice');
Route::get('pinjaman/cetak/{id}', [PaidController::class, 'cetak'])->name('cetak');



// Laporan
Route::get('laporan', [PinjamanController::class, 'laporan'])->name('laporan');
Route::get('laporan/cetak-pinjaman', [PinjamanController::class, 'cetak_pinjaman'])->name('cetak.pinjaman');
Route::get('laporan/cetak-cheque', [PinjamanController::class, 'cetak_laporan_cheque'])->name('cetak.laporan.cheque');
Route::get('laporan/cetak-cheque/{id}', [PinjamanController::class, 'cetak_cheque'])->name('cetak.cheque');


// RESOURCE
Route::resource('user', UserController::class);
Route::resource('peminjam', PeminjamController::class);
Route::resource('pinjaman', PinjamanController::class);
Route::resource('cheque', ChequeController::class);


});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'divisi', 'role', 'image', 'last_login'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;
use Yajra\DataTables\DataTables;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Storage;

class UserController extends Controller
{
    public function dataJson()
    {
        return DataTables::of(User::orderByDesc('id')->get())
            ->addColumn('action', function ($row) {
                // <a href="'.route("user.show", $row->id).'" class="btn btn-info shadow btn-md me-1"><i class="fa fa-eye text-white"></i></a>

                $action = '<a href="javascript:void(0);" class="btn btn-md btn-edit" data-id="' . $row->id . '" data-name="' . $row->name . '" data-email="' . $row->email . '" data-divisi="' . $row->divisi . '" data-role="' . $row->role . '"><i class="bx bxs-edit"></i></a> <a href="javascript:void(0);" data-id="' . $row->id . '" class="btn btn-md btn-delete"><i class="bx bxs-trash"></i></a>';
                return $action;
            })
            ->addIndexColumn()
            ->make(true);

    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        
        return view('user.index');

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        
        $request->validate([
            'name' => 'required',
            'divisi' => 'required',
        ]);

        $req_user = $request->all();

        if ($request->id) {

            $user = User::find($request->id);

            $image = $user->image;

        if ($request->hasFile('image')) {
            File::delete($user->image);
            
            // if ($user->image && Storage::exists($user->image)) {
            //     Storage::delete($user->image);
            // }
            
            $image = 'uploads/images/profile/'. time() . '_' . $request->file('image')->getClientOriginalName();
            $request->file('image')->move('uploads/images/profile', $image);

        }
            $req_user['image'] = $image;

            $user->update($req_user);
            $message = "Data User Berhasil diupdate";


        } else {

            if ($request->hasFile('image')) {
                $image = 'uploads/images/profile/'. time() . '_' . $request->file('image')->getClientOriginalName(); 
                $request->file('image')->move('uploads/images/profile', $image);
                
                $req_user['image'] = $image;
            }
            $user = User::create($req_user);
            $message = "Data User Berhasil Disimpan";

        }

        return back()->with('success', $message);

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function ubah_pass(Request $request)
    {
        $user = User::find($request->id);

        User::where('id', $user->id)
        ->update([
            'password' => Hash::make($request->password),
        ]);
        return back()->with('success', 'Password telah diubah');

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function profil()
    {
        $profil = auth()->user();

        return view('user.profile', compact('profil'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::find($id);
        $user->delete();

        return back();

    }
}

resources/views/user/index.blade.php
@extends('backend.index')
@section('title', 'Data User')
@section('isi-konten')
<!-- Content -->
<div class="container-xxl flex-grow-1 container-p-y">

    <h4 class="fw-bold py-3 mb-4">
        <span class="text-muted fw-light">Dashboard /</span> User
    </h4>

    <button class="btn btn-primary add-btn mb-3" data-toggle="modal" data-target="#modal_user"> <i class="bx bx-plus bx-xs"></i> Tambah</button>

    <!-- Bordered Table -->
    <div class="card">
        <h5 class="card-header">Data User</h5>
        <div class="card-body">
            <div class="table-responsive text-nowrap">
                <table class="table table-bordered" id="my-datatable">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Nama</th>
                            <th>Email</th>
                            <th width="10">Divisi</th>
                            <th width="10">Actions</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
    <!--/ Bordered Table -->
</div>
<!-- / Content -->

{{-- Modal start --}}

<div id="modal_user_add" class="modal custom-modal fade" role="dialog">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"><span>Tambah</span> User</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="POST" action="{{ route('user.store') }}">
                    <div class="row">
                    @csrf
                    <input type="hidden" id="id" name="id">
                    <div class="form-group">
                        <label class="col-form-label">Nama Pengguna<span class="text-danger">*</span></label>
                        <input class="form-control" id="name" name="name" type="text" placeholder="Masukkan Nama Pengguna" required>
                    </div>
                    <div class="form-group mb-3">
                        <label class="col-form-label">Email<span class="text-danger">*</span></label>
                        <input class="form-control" id="email" name="email" type="email" placeholder="Masukkan Email" required>
                    </div>
                    <div class="form-group mb-3">
                        <label class="col-form-label">Divisi<span class="text-danger">*</span></label>
                        <select name="divisi" id="divisi" class="form-control">
                            <option>- Pilih -</option>
                            <option value="dibur">CO Disbursement</option>
                            <option value="vt">CO VT Management</option>
                            <option value="ic">Internal Control</option>
                        </select>
                    </div>
                    <div class="form-group mb-3">
                        <label class="col-form-label">Password<span class="text-danger">*</span></label>
                        <input class="form-control" id="password" name="password" type="password" placeholder="Masukkan Password" required>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Close</button>
                        <button class="btn btn-primary">Simpan</button>
                    </div>
                </div>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modal_user" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="modalCenterTitle">Edit User</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <form method="POST" action="{{ route('user.store') }}">
                @csrf
                <input type="hidden" id="id" name="id">
                <div class="row">
                    <div class="col-md-12 mb-2">
                        <label for="nama" class="form-label">Nama Pengguna<span class="text-danger">*</span></label>
                        <input type="text" id="name" name="name" class="form-control" placeholder="Masukkan Nama Pengguna" required>
                    </div>
                    <div class="col-md-12 mb-2">
                        <label for="email" class="form-label">Email<span class="text-danger">*</span></label>
                        <input type="email" id="email" name="email" class="form-control" placeholder="xxxx@xxx.xx" required>
                    </div>
                    <div class="col-md-12 mb-2">
                        <label for="divisi" class="form-label">Divisi</label>
                        <select name="divisi" id="divisi" class="form-control">
                            <option>- Pilih -</option>
                            <option value="dibur">CO Disbursement</option>
                            <option value="vt">CO VT Management</option>
                            <option value="ic">Internal Control</option>
                        </select>
                    </div>
                </div>
                <div class="modal-footer">
                    {{-- <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Tutup</button> --}}
                    <button class="btn btn-primary">Simpan</button>
                </div>
            </form>
            <form method="POST" action="{{ route('ubah_pass') }}">
                @csrf
                @method('patch')

                <input type="hidden" id="id" name="id">
                <div class="col-md-12">
                    <label for="password" class="form-label">Password</label>
                    <input type="password" name="password" id="password" class="form-control" placeholder="Masukkan Password">
                </div>
                
                <div class="modal-footer">
                    <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Tutup</button>
                    <button class="btn btn-primary">Simpan</button>
                </div>
            </form>
      </div>
    </div>
  </div>

{{-- Modal end --}}

{{-- Delete Job Modal start --}}

<div class="modal custom-modal fade" id="delete_pkpt" role="dialog">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-body">
                <div class="modal-header">
                    <h2 class="modal-title" id="exampleModalLongTitle">Hapus</h2>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <h4 class="text-center">Anda yakin ingin hapus?</h4>
                <div class="modal-btn delete-action">
                    <div class="row">
                        <div class="col-6">
                            <form method="POST" id="url-delete">
                                @method('DELETE')
                                @csrf
                                <button class="btn btn-primary continue-btn w-100" type="submit">Delete</button>
                            </form>
                        </div>
                        <div class="col-6">
                            <button type="button" data-dismiss="modal" class="btn btn-primary">Cancel</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{{-- Delete Job Modal end --}}

{{-- modal end --}}
@endsection
@push ('page-scripts')
{{-- <script>
        var table = $("#my-datatable").DataTable();

</script> --}}

<script>
    $(document).ready(function() {
        var table = $("#my-datatable").DataTable({
            processing: true,
            serverSide: true,
            ajax: "{{ route('user.json') }}",
            columns: [
                {
                    data: "DT_RowIndex",
                    name: "DT_RowIndex",
                },
                {
                    data: "name",
                    name: "name",
                    // render: function(data, type, row) {
                    //     var url = "{{ url('pkpt/risk-register') }}/"+row.id;
                    //     return `<a href="${url}">${data}</a>`;
                    // }
                },
                {
                    data: "email",
                    name: "email"
                },
                {
                    data: "divisi",
                    name: "divisi"
                },
                {
                    data: "action",
                    name: "action",
                    className: 'text-center'
                },
            ],
            order: [[ 0, "desc" ]]
        });

        table.on('draw.dt', function () {
            var info = table.page.info();
            table.column(0, {
                search: 'applied', order: 'applied', page: 'applied'
            }).nodes().each(function (cell, i) {
                cell.innerHTML = i + 1 + info.start;
            });
        });

        // add user
        $('.add-btn').on('click', function(){            
            $('#modal_user_add .modal-title span').html('Tambah');
            $('#modal_user_add #id').val('');
            $('#modal_user_add form').trigger('reset');


            var myModal = new bootstrap.Modal(document.getElementById('modal_user_add'))
            myModal.show()
        });

        // edit user
        $("#my-datatable").on("click", ".btn-edit", function(e) {
            e.preventDefault();
            data = $(this).data();

            $.each(data, function(index, value){
                $('#modal_user #'+index).val(value);
            })

            $('#modal_user'+' .modal-title span').html('Edit');

            var myModal = new bootstrap.Modal(document.getElementById('modal_user'))
            myModal.show()
        });

        // delete user
        $("#my-datatable").on("click", ".btn-delete", function(e) {
            e.preventDefault();
            const id = $(this).data("id");
            $('#delete_pkpt #url-delete').attr('action', "{{ url('user') }}/"+id);

    swal({
        title: 'Kamu Yakin Mau Hapus?',
        text: 'Jika di Hapus, Data akan hilang!',
        icon: 'warning',
        buttons: true,
        dangerMode: true,
      })
      .then((willDelete) => {
        if (willDelete) {
        swal('Data Berhasil diHapus :)', {
          icon: 'success',
        });
        $(`#url-delete`).submit();
        } else {
        swal('Data Kamu Aman!');
        }
      });
            // var myModal = new bootstrap.Modal(document.getElementById('delete_pkpt'))
            // myModal.show()
        });

    });
</script>
@endpush

resources/views/user/profile.blade.php
@extends('backend.index')
@section('title', 'Profil')
@section('isi-konten')
<!-- Content -->
<div class="container-xxl flex-grow-1 container-p-y">

    <h4 class="fw-bold py-3 mb-4">
        <span class="text-muted fw-light">Dashboard /</span> Profil
    </h4>

    <div class="row">
        <div class="col-md-12">
          <div class="card mb-4">
            <h5 class="card-header">Profile Details</h5>
            <!-- Account -->
            <div class="card-body">
              <div class="d-flex align-items-start align-items-sm-center gap-4">
                <img
                  src="{{ $profil->image }}"
                  alt="user-avatar"
                  class="d-block rounded"
                  height="100"
                  width="100"
                  id="uploadedAvatar"
                />
                <form id="formAccountSettings" method="POST" action="{{ route('user.store') }}" enctype="multipart/form-data">
                    @csrf
                <div class="button-wrapper">
                  <label for="image" class="btn btn-primary me-2 mb-4" tabindex="0">
                    <span class="d-none d-sm-block">Upload new photo</span>
                    <i class="bx bx-upload d-block d-sm-none"></i>
                    <input
                      type="file"
                      id="image"
                      {{-- class="account-file-input" --}}
                      hidden
                      name="image"
                      {{-- accept="image/png, image/jpeg" --}}
                    />
                  </label>
                  {{-- <button type="button" class="btn btn-outline-secondary account-image-reset mb-4">
                    <i class="bx bx-reset d-block d-sm-none"></i>
                    <span class="d-none d-sm-block">Reset</span>
                  </button> --}}

                  <p class="text-muted mb-0">Allowed JPG or PNG.</p>
                </div>
              </div>
            </div>
            <hr class="my-0" />
            <div class="card-body">
                <div class="row">
                  <div class="mb-3 col-md-6">
                    <input type="text" id="id" name="id" value="{{ $profil->id }}" hidden>
                    <label for="name" class="form-label">Nama</label>
                    <input
                      class="form-control"
                      type="text"
                      id="name"
                      name="name"
                      value="{{ $profil->name }}"
                      autofocus
                    />
                  </div>
                  <div class="mb-3 col-md-6">
                    <label for="divisi" class="form-label">Divisi</label>
                    <input class="form-control" type="text" name="divisi" id="divisi" value="{{ $profil->divisi }}" />
                  </div>
                  <div class="mb-3 col-md-6">
                    <label for="email" class="form-label">E-mail</label>
                    <input
                      class="form-control"
                      type="email"
                      id="email"
                      name="email"
                      value="{{ $profil->email }}"
                      placeholder="xxx@xxx.xxx"
                    />
                  </div>
                </div>
                <div class="mt-2">
                  <button type="submit" class="btn btn-primary me-2">Save changes</button>
                  <a href="/" class="btn btn-outline-secondary">Cancel</a>
                </div>
              </form>
            </div>
            <!-- /Account -->
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-12">
          <div class="card mb-4">
            <h5 class="card-header">Ubah Password</h5>
            <!-- Account -->
            <div class="card-body">
              <form id="formAccountSettings" method="POST" action="{{ route('ubah_pass') }}">
                @csrf
                @method('patch')

                <div class="row">
                  <input type="text" id="id" name="id" value="{{ $profil->id }}" hidden>
                  <div class="mb-3 col-md-6">
                    <label for="password" class="form-label">Password</label>
                    <input type="password" class="form-control" id="password" name="password" value="" placeholder="&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;"
                    />
                  </div>
                </div>
                <div class="mt-2">
                  <button type="submit" class="btn btn-primary me-2">Save changes</button>
                  <a href="/" class="btn btn-outline-secondary">Cancel</a>
                </div>
              </form>
            </div>
            <!-- /Account -->
          </div>
        </div>
      </div>
    </div>
    <!-- / Content -->
</div>
<!-- / Content -->
@endsection
@push ('page-scripts')
<script>
        var table = $("#my-datatable").DataTable();

</script>
@endpush