routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PaidController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ChequeController;
use App\Http\Controllers\PendingController;
use App\Http\Controllers\PeminjamController;
use App\Http\Controllers\PinjamanController;
use App\Http\Controllers\VerificationController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('user.content');
// });


Auth::routes();

Route::get('/', function () {
    return redirect(route('login'));
});

Route::group(['middleware' => 'auth'], function() {

Route::get('/dashboard', [HomeController::class, 'index'])->name('home');
Route::get('/profil', [UserController::class, 'profil'])->name('profil');


// DATA JSON
Route::get('/user/datajson', [UserController::class, 'dataJson'])->name('user.json');
Route::get('/peminjam/datajson', [PeminjamController::class, 'dataJson'])->name('peminjam.json');
Route::get('/peminjam/pinjaman/datajson', [PeminjamController::class, 'dataJson_pinjaman'])->name('peminjam.pinjam.json');
Route::get('/pinjaman/datajson/{id}', [PinjamanController::class, 'dataJson'])->name('pinjaman.json');
Route::get('/verification/datajson/{id}', [VerificationController::class, 'dataJson_pinjaman'])->name('verif.json');
Route::get('/verification/peminjam/datajson', [VerificationController::class, 'dataJson_peminjam'])->name('peminjam.verif.json');
Route::get('/pending/datajson/{id}', [PendingController::class, 'dataJson_pinjaman'])->name('pending.json');
Route::get('/pending/peminjam/datajson', [PendingController::class, 'dataJson_peminjam'])->name('peminjam.pending.json');
Route::get('/paid/datajson/{id}', [PaidController::class, 'dataJson_pinjaman'])->name('paid.json');
Route::get('/paid/peminjam/datajson', [PaidController::class, 'dataJson_peminjam'])->name('peminjam.paid.json');
Route::get('/cheque/datajson', [ChequeController::class, 'dataJson'])->name('cheque.json');

Route::patch('/ubah_pass', [UserController::class, 'ubah_pass'])->name('ubah_pass');
Route::get('/peminjam/pinjaman/{id}', [PinjamanController::class, 'index_pinjaman'])->name('peminjam.pinjaman');


Route::get('verification', [VerificationController::class, 'index'])->name('index.verification');
Route::post('verification/update', [VerificationController::class, 'verif'])->name('update.verif');
Route::get('/peminjam/verification/{id}', [VerificationController::class, 'index_pinjaman'])->name('peminjam.verif');

Route::get('pending', [PendingController::class, 'index'])->name('index.pending');
Route::post('pending/update', [PendingController::class, 'pending'])->name('update.pending');
Route::get('/peminjam/pending/{id}', [PendingController::class, 'index_pinjaman'])->name('peminjam.pending');

Route::get('pending', [PendingController::class, 'index'])->name('index.pending');
Route::post('pending/update', [PendingController::class, 'pending'])->name('update.pending');
Route::get('/peminjam/pending/{id}', [PendingController::class, 'index_pinjaman'])->name('peminjam.pending');

Route::get('paid', [PaidController::class, 'index'])->name('index.paid');
Route::get('/peminjam/paid/{id}', [PaidController::class, 'index_pinjaman'])->name('peminjam.paid');

Route::get('riwayat/{id}', [PaidController::class, 'riwayat'])->name('riwayat');
Route::get('invoice/{id}', [PendingController::class, 'invoice'])->name('invoice');
Route::get('pinjaman/cetak/{id}', [PaidController::class, 'cetak'])->name('cetak');



// Laporan
Route::get('laporan', [PinjamanController::class, 'laporan'])->name('laporan');
Route::get('laporan/cetak-pinjaman', [PinjamanController::class, 'cetak_pinjaman'])->name('cetak.pinjaman');
Route::get('laporan/cetak-cheque', [PinjamanController::class, 'cetak_laporan_cheque'])->name('cetak.laporan.cheque');
Route::get('laporan/cetak-cheque/{id}', [PinjamanController::class, 'cetak_cheque'])->name('cetak.cheque');


// RESOURCE
Route::resource('user', UserController::class);
Route::resource('peminjam', PeminjamController::class);
Route::resource('pinjaman', PinjamanController::class);
Route::resource('cheque', ChequeController::class);


});

app/Http/Controllers/VerificationController.php
<?php

namespace App\Http\Controllers;

use Carbon\Carbon;
use App\Models\Riwayat;
use App\Models\Peminjam;
use App\Models\Pinjaman;
use Illuminate\Http\Request;
use Yajra\DataTables\DataTables;
use Auth;

class VerificationController extends Controller
{

    public function dataJson_peminjam()
    {
        return DataTables::of(Peminjam::orderByDesc('id')->get())
            ->addColumn('action', function ($row) {
               $lihat= '<a href="'.route("peminjam.verif", $row->id).'" class="btn btn-md me-1"><i class="bx bxs-show"></i></a>';

                // $action = '<a href="javascript:void(0);" class="btn btn-md btn-edit" data-id="' . $row->id . '" data-nama_peminjam="' . $row->nama_peminjam . '" data-alamat="' . $row->alamat . '"><i class="bx bxs-edit"></i></a> <a href="javascript:void(0);" data-id="' . $row->id . '" class="btn btn-md btn-delete"><i class="bx bxs-trash"></i></a>';

                return $lihat;
            })
            ->addIndexColumn()
            ->make(true);
    }

    public function dataJson_pinjaman($id)
    {
        $today = Carbon::now();

        return DataTables::of(Pinjaman::where('peminjam_id', $id)
        ->whereBetween('tgl_jatuh_tempo', [$today, $today->copy()->addDays(7)])
        ->join('tipe_pinjaman', 'pinjaman.tipe_pinjaman_id', '=', 'tipe_pinjaman.id')
        ->join('peminjam', 'pinjaman.peminjam_id', '=', 'peminjam.id')
        ->where('status_pembayaran', 'Pending')
        ->select('pinjaman.id as id', 'pinjaman.*', 'tipe_pinjaman.nama', 'tipe_pinjaman.kode', 'peminjam.nama_peminjam')
        ->orderByDesc('pinjaman.id')->get())
        
        ->addColumn('action', function ($row) {
                if (Auth::user()->role == 'vt') {
                    $action = '
                    <a href="javascript:void(0);"
                    data-no_pinjaman="'.$row->no_pinjaman.'" 
                    data-nama_peminjam="'.$row->nama_peminjam.'" 
                    data-nama="'.$row->nama.'" 
                    data-tgl_pencairan="'.Carbon::parse($row->tgl_pencairan)->translatedformat('d F Y').'" 
                    data-tgl_jatuh_tempo="'.Carbon::parse($row->tgl_jatuh_tempo)->translatedformat('d F Y').'" 
                    data-nominal_pinjaman="'.$row->nominal_pinjaman.'" 
                    data-nama_payor="'.$row->nama_payor.'" 
                    data-no_invoice="'.$row->no_invoice.'" 
                    data-dokumen="'.$row->dokumen.'" 
                    data-tgl_validasi="'.Carbon::parse($row->tgl_validasi)->translatedformat('d F Y').'" 
                    data-note="'.$row->note.'" 
                    class="btn btn-md btn-detail"><i class="bx bxs-show"></i></a>
                    
                    <a href="javascript:void(0);" class="btn btn-md btn-edit" data-id="' . $row->id .'" data-tgl_validasi="' . $row->tgl_validasi .'" data-status_pembayaran="' . $row->status_pembayaran .'" data-tipe_pinjaman_id="' . $row->tipe_pinjaman_id . '" data-kode="' . $row->kode . '" data-no_invoice="' . $row->no_invoice . '"><i class="bx bxs-edit"></i></a>';

                    return $action;
                }
            })
            ->addColumn('tgl_pencairan', function ($row) {
                $tgl = Carbon::parse($row->tgl_pencairan)->translatedFormat('d F Y');
                    return $tgl;
            })
            ->addColumn('tgl_jatuh_tempo', function ($row) {
                $tgl = Carbon::parse($row->tgl_pencairan)->translatedFormat('d F Y');
                    return $tgl;
            })
            ->addIndexColumn()
            ->make(true);

    }

    public function index()
    {
        return view('verification.index_peminjam');
    }

    public function index_pinjaman($id)
    {
        $peminjam = Peminjam::find($id);

        return view('verification.index', compact('peminjam'));
    }

    public function verif(Request $request)
    {
        $pinjaman = Pinjaman::find($request->id);

        $req_form = $request->all();

        
        $req_form['user_id'] = Auth::user()->id;
        $req_form['posisi'] = 'Pending Verification';
        $req_form['pinjaman_id'] = $pinjaman->id;
        
        $pinjaman->update($req_form);
        $riwayat = Riwayat::create($req_form);

        return back()->with('success', 'Verification Berhasil Disimpan');
    }
}

resources/views/verification/index.blade.php
@extends('backend.index')
@section('title', 'Data Pinjaman')
@section('isi-konten')
<!-- Content -->
<div class="container-xxl flex-grow-1 container-p-y">

    <h4 class="fw-bold py-3 mb-4">
        <span class="text-muted fw-light">Dashboard /</span> Invoice Pending Verification
    </h4>

    {{-- <button class="btn btn-primary add-btn mb-3" data-toggle="modal" data-target="#modal_pinjaman"> <i class="bx bx-plus bx-xs"></i> Tambah</button> --}}

    <!-- Bordered Table -->
    <div class="card">
        <h5 class="card-header">Data Pinjaman</h5>
        <div class="card-body">
            <div class="table-responsive text-nowrap">
                <table class="table table-bordered" id="my-datatable">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Tipe Pinjaman</th>
                            <th>Nomor Pinjaman</th>
                            <th>Tanggal Pencairan</th>
                            <th>Tanggal Jatuh Tempo</th>
                            <th>Nama Payor</th>
                            <th>Status Pembayaran</th>
                            @if (Auth::user()->role == 'vt')
                            <th width="80">Actions</th>
                            @endif
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
    <!--/ Bordered Table -->
</div>
<!-- / Content -->

{{-- Modal start --}}

{{-- <div id="modal_pinjaman" class="modal custom-modal fade" role="dialog">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"><span>Tambah</span> Risk Register</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row">
                <form method="POST" action="">
                    @csrf
                    <input type="hidden" id="id" name="id">
                    <div class="form-group">
                        <label class="col-form-label">Nama<span class="text-danger">*</span></label>
                        <input class="form-control" id="nama" name="nama" type="text" required>
                    </div>
                    <div class="form-group mb-3">
                        <label class="col-form-label">Kategori<span class="text-danger">*</span></label>
                        <input class="form-control" id="kategori" name="kategori" type="text" required>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-primary">Simpan</button>
                    </div>
                </form>
                </div>
            </div>
        </div>
    </div>
</div> --}}

<div class="modal fade" id="modal_pinjaman" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="modalCenterTitle"><span>Edit</span> Pinjaman</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <form method="POST" action="{{ route('update.verif') }}" enctype="multipart/form-data">
                @csrf
                <input type="hidden" id="id" name="id">
                <div class="row">
                    <div class="col-md-12 mb-2">
                        <label for="tgl_validasi" class="form-label">Tanggal Validasi <span class="text-danger">*</span></label>
                        <input type="date" id="tgl_validasi" name="tgl_validasi" class="form-control" required>
                    </div>
                    <div class="col-md-12 mb-2">
                        <label for="note" class="form-label">Note</label>
                        <input type="text" id="note" name="note" class="form-control">
                    </div>
                    <div class="col-md-12 mb-2">
                        <label for="status_pembayaran" class="form-label">Status Pembayaran</label>
                        <select name="status_pembayaran" id="status_pembayaran" class="form-control">
                            <option value="">- Pilih -</option>
                            <option value="Paid">Paid</option>
                        </select>
                    </div>
                </div>
            </div>
                <div class="modal-footer">
                    {{-- <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Tutup</button> --}}
                    <button class="btn btn-primary">Update</button>
                </div>
            </form>
    </div>
  </div>
</div>

{{-- Modal end --}}

{{-- Modal Detail start --}}

<div class="modal fade" id="modal_pinjaman_detail" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-md" role="document">
        <div class="modal-content">
            <div class="modal-header">
                    <h5 class="modal-title" id="modalCenterTitle">Detail Pinjaman</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
                <div class="modal-body">
                        <table class="table table-border">
                                <tr>
                                    <td>Nomor Pinjaman</td>
                                    <td>:</td>
                                    <td class="text-end" id="no_pinjaman"></td>
                                </tr>
                                <tr>
                                    <td>Nama Peminjam</td>
                                    <td>:</td>
                                    <td class="text-end" id="nama_peminjam"></td>
                                </tr>
                                <tr>
                                    <td>Tipe Pinjaman</td>
                                    <td>:</td>
                                    <td class="text-end" id="nama"></td>
                                </tr>
                                <tr>
                                    <td>Tanggal Pencairan</td>
                                    <td>:</td>
                                    <td class="text-end" id="tgl_pencairan"></td>
                                </tr>
                                <tr>
                                    <td>Tanggal Jatuh Tempo</td>
                                    <td>:</td>
                                    <td class="text-end" id="tgl_jatuh_tempo"></td>
                                </tr>
                                <tr>
                                    <td>Nominal Pinjaman</td>
                                    <td>:</td>
                                    <td class="text-end" id="nominal_pinjaman"></td>
                                </tr>
                                <tr>
                                    <td>Nama Payor</td>
                                    <td>:</td>
                                    <td class="text-end" id="nama_payor"></td>
                                </tr>
                                <tr>
                                    <td>Nomor Invoice</td>
                                    <td>:</td>
                                    <td class="text-end" id="no_invoice"></td>
                                </tr>
                                <tr>
                                    <td>Dokumen</td>
                                    <td>:</td>
                                    <td class="text-end" id="dokumen"></td>
                                </tr>
                                <tr>
                                    <td>Tanggal Validasi</td>
                                    <td>:</td>
                                    <td class="text-end" id="tgl_validasi"></td>
                                </tr>
                        </table>
            </div>
        </div>
    </div>
</div>

{{-- modal end --}}

@endsection
@push ('page-scripts')
{{-- <script>
        var table = $("#my-datatable").DataTable();

</script> --}}

<script>
    $(document).ready(function() {
        const id_peminjam = $(this).data("id");

        var table = $("#my-datatable").DataTable({
            processing: true,
            serverSide: true,
            ajax: "{{ route('verif.json', ['id'=>$peminjam->id]) }}",
            columns: [
                {
                    data: "DT_RowIndex",
                    name: "DT_RowIndex",
                },
                {
                    data: "nama",
                    name: "nama",
                    // render: function(data, type, row) {
                    //     var url = "{{ url('pkpt/risk-register') }}/"+row.id;
                    //     return `<a href="${url}">${data}</a>`;
                    // }
                },
                {
                    data: "no_pinjaman",
                    name: "no_pinjaman"
                },
                {
                    data: "tgl_pencairan",
                    name: "tgl_pencairan"
                },
                {
                    data: "tgl_jatuh_tempo",
                    name: "tgl_jatuh_tempo"
                },
                {
                    data: "nama_payor",
                    name: "nama_payor"
                },
                {
                    data: "status_pembayaran",
                    name: "status_pembayaran"
                },
                @if (Auth::user()->role == 'vt')
                {
                    data: "action",
                    name: "action",
                    className: 'text-center'
                },
                @endif
            ],
            order: [[ 0, "desc" ]]
        });

        table.on('draw.dt', function () {
            var info = table.page.info();
            table.column(0, {
                search: 'applied', order: 'applied', page: 'applied'
            }).nodes().each(function (cell, i) {
                cell.innerHTML = i + 1 + info.start;
            });
        });

        // add pinjaman
        $('.add-btn').on('click', function(){            
            $('#modal_pinjaman .modal-title span').html('Tambah');
            $('#modal_pinjaman #id').val('');
            $('#modal_pinjaman form').trigger('reset');


            var myModal = new bootstrap.Modal(document.getElementById('modal_pinjaman'))
            myModal.show()
        });

        // edit pinjaman
        $("#my-datatable").on("click", ".btn-edit", function(e) {
            e.preventDefault();
            data = $(this).data();

            $.each(data, function(index, value){

                $('#modal_pinjaman #'+index).val(value);
            })


            $('#modal_pinjaman'+' .modal-title span').html('Edit');

            var myModal = new bootstrap.Modal(document.getElementById('modal_pinjaman'))
            myModal.show()
        });

        // detail pinjaman
        $("#my-datatable").on("click", ".btn-detail", function(e) {
            e.preventDefault();
            data = $(this).data();
    
            $.each(data, function(index, value){
            if (index === 'dokumen') {
            
                var url = window.location.origin + '/' + value;
                var link = '<a href="' + url + '" target="_blank" class="btn btn-success btn-sm">Lihat</a>';

                $('#modal_pinjaman_detail #'+index).html(link);

            } else if (index === 'nominal_pinjaman') { 

                var rupiah = formatRupiah(value);
                $('#modal_pinjaman_detail #'+index).html(rupiah);

            } else if (index === 'no_invoice') {
                
                var no_invoice = value.split(",");
                var enter_kebawah = no_invoice.join("<br>");

                $('#modal_pinjaman_detail #'+index).html(enter_kebawah);

            } else  {

                $('#modal_pinjaman_detail #'+index).html(value);
            }
            })
            
            // Fungsi untuk mengubah nilai menjadi format rupiah
            function formatRupiah(value) {
                var formatter = new Intl.NumberFormat('id-ID', {
                    style: 'currency',
                    currency: 'IDR',
                    minimumFractionDigits: 0 
                });
                return formatter.format(value);
            }            
            
                var myModal = new bootstrap.Modal(document.getElementById('modal_pinjaman_detail'))
            myModal.show()
            
        });

    });

</script>
@endpush

resources/views/verification/index_peminjam.blade.php
@extends('backend.index')
@section('title', 'Invoice Pending Verification')
@section('isi-konten')
<!-- Content -->
<div class="container-xxl flex-grow-1 container-p-y">

    <h4 class="fw-bold py-3 mb-4">
        <span class="text-muted fw-light">Dashboard /</span> Invoice Pending Verification
    </h4>

    {{-- <button class="btn btn-primary add-btn mb-3" data-toggle="modal" data-target="#modal_peminjam"> <i class="bx bx-plus bx-xs"></i> Tambah</button> --}}

    <!-- Bordered Table -->
    <div class="card">
        <h5 class="card-header">Data Peminjam</h5>
        <div class="card-body">
            <div class="table-responsive text-nowrap">
                <table class="table table-bordered" id="my-datatable">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Nama</th>
                            <th>Email</th>
                            <th>Alamat</th>
                            <th width="10">Actions</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
    <!--/ Bordered Table -->
</div>
<!-- / Content -->

{{-- Modal start --}}

{{-- <div id="modal_peminjam" class="modal custom-modal fade" role="dialog">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"><span>Tambah</span> Risk Register</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row">
                <form method="POST" action="">
                    @csrf
                    <input type="hidden" id="id" name="id">
                    <div class="form-group">
                        <label class="col-form-label">Nama<span class="text-danger">*</span></label>
                        <input class="form-control" id="nama" name="nama" type="text" required>
                    </div>
                    <div class="form-group mb-3">
                        <label class="col-form-label">Kategori<span class="text-danger">*</span></label>
                        <input class="form-control" id="kategori" name="kategori" type="text" required>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-primary">Simpan</button>
                    </div>
                </form>
                </div>
            </div>
        </div>
    </div>
</div> --}}

<div class="modal fade" id="modal_peminjam" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="modalCenterTitle"><span>Tambah</span> Peminjam</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <form method="POST" action="{{ route('peminjam.store') }}">
                @csrf
                <input type="hidden" id="id" name="id">
                <div class="row">
                    <div class="col-md-12 mb-2">
                        <label for="nama_peminjam" class="form-label">Nama Peminjam<span class="text-danger">*</span></label>
                        <input type="text" id="nama_peminjam" name="nama_peminjam" class="form-control" placeholder="Masukkan Nama Peminjam" required>
                    </div>
                    <div class="col-md-12">
                        <label for="alamat" class="form-label">Alamat<span class="text-danger">*</span></label>
                        <input type="text" id="alamat" name="alamat" class="form-control" placeholder="Masukkan Alamat" required>
                    </div>
                </div>
            </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Tutup</button>
                    <button class="btn btn-primary">Simpan</button>
                </div>
            </form>
    </div>
  </div>

{{-- Modal end --}}

{{-- Delete Job Modal start --}}

<div class="modal custom-modal fade" id="delete_peminjam" role="dialog">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-body">
                <div class="modal-header">
                    <h2 class="modal-title" id="exampleModalLongTitle">Hapus</h2>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <h4 class="text-center">Anda yakin ingin hapus?</h4>
                <div class="modal-btn delete-action">
                    <div class="row">
                        <div class="col-6">
                            <form method="POST" id="url-delete">
                                @method('DELETE')
                                @csrf
                                <button class="btn btn-primary continue-btn w-100" type="submit">Delete</button>
                            </form>
                        </div>
                        <div class="col-6">
                            <button type="button" data-dismiss="modal" class="btn btn-primary">Cancel</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{{-- Delete Job Modal end --}}

{{-- modal end --}}
@endsection
@push ('page-scripts')
{{-- <script>
        var table = $("#my-datatable").DataTable();

</script> --}}

<script>
    $(document).ready(function() {
        var table = $("#my-datatable").DataTable({
            processing: true,
            serverSide: true,
            ajax: "{{ route('peminjam.verif.json') }}",
            columns: [
                {
                    data: "DT_RowIndex",
                    name: "DT_RowIndex",
                },
                {
                    data: "nama_peminjam",
                    name: "nama_peminjam",
                    // render: function(data, type, row) {
                    //     var url = "{{ url('pkpt/risk-register') }}/"+row.id;
                    //     return `<a href="${url}">${data}</a>`;
                    // }
                },
                {
                    data: "email",
                    name: "email"
                },
                {
                    data: "alamat",
                    name: "alamat"
                },
                {
                    data: "action",
                    name: "action",
                    className: 'text-center'
                },
            ],
            order: [[ 0, "desc" ]]
        });

        table.on('draw.dt', function () {
            var info = table.page.info();
            table.column(0, {
                search: 'applied', order: 'applied', page: 'applied'
            }).nodes().each(function (cell, i) {
                cell.innerHTML = i + 1 + info.start;
            });
        });

        // add Peminjam
        $('.add-btn').on('click', function(){            
            $('#modal_peminjam .modal-title span').html('Tambah');
            $('#modal_peminjam #id').val('');
            $('#modal_peminjam form').trigger('reset');


            var myModal = new bootstrap.Modal(document.getElementById('modal_peminjam'))
            myModal.show()
        });

        // edit Peminjam
        $("#my-datatable").on("click", ".btn-edit", function(e) {
            e.preventDefault();
            data = $(this).data();

            $.each(data, function(index, value){
                $('#modal_peminjam #'+index).val(value);
            })

            $('#modal_peminjam'+' .modal-title span').html('Edit');

            var myModal = new bootstrap.Modal(document.getElementById('modal_peminjam'))
            myModal.show()
        });

        // delete Peminjam
        $("#my-datatable").on("click", ".btn-delete", function(e) {
            e.preventDefault();
            const id = $(this).data("id");
            $('#delete_peminjam #url-delete').attr('action', "{{ url('peminjam') }}/"+id);

    swal({
        title: 'Kamu Yakin Mau Hapus?',
        text: 'Jika di Hapus, Data akan hilang!',
        icon: 'warning',
        buttons: true,
        dangerMode: true,
      })
      .then((willDelete) => {
        if (willDelete) {
        swal('Data Berhasil diHapus :)', {
          icon: 'success',
        });
        $(`#url-delete`).submit();
        } else {
        swal('Data Kamu Aman!');
        }
      });
            // var myModal = new bootstrap.Modal(document.getElementById('delete_peminjam'))
            // myModal.show()
        });

    });
</script>
@endpush